version: '2.2'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - $PWD/data/redis:/var/lib/redis
      - $PWD/data/redis.conf:/usr/local/etc/redis/redis.conf
